/**
 * Created by Increment on 04.09.2016.
 */
export const CALENDAR_ADD_TASK = 'CALENDAR_ADD_TASK';
export const CALENDAR_GET_TASK = 'CALENDAR_GET_TASK';
export const CALENDAR_GET_TASK_ERR = 'CALENDAR_GET_TASK_ERR';
export const CALENDAR_CHANGE_SELECT_DAY = 'CALENDAR_CHANGE_SELECT_DAY';
export const CALENDAR_ADD_TASK_ERR = 'CALENDAR_ADD_TASK_ERR';
export const CALENDAR_CHANGE_MONTH = 'CALENDAR_CHANGE_MONTH';